### ISSUE TITLE
Развернуть CRA для первого примера самого простого использования пакета react-uikit

### ISSUE THREAD

**Issue by LordWerter** [LordWerter/fast-js#1]
В корне репозитория есть дирректория examples. В ней надо создать через CRA приложение react-uikit и прикрутить туда в качестве основных зависимостей пакеты:
  * @emotion/react
  * @emotion/styled
  * @fast-js/react-uikit
  * @fast-js/utils
  * @rematch/core
  * axios
  * prop-types
  * react
  * react-dom
  * react-redux
  * react-router-dom
  * redux
  * web-vitals

В качестве devDependencies установить:
  * @fast-js/types
  * @fast-js/eslint
  * @fast-js/jest
  * @fast-js/prettier
  * @types/jest
 * @types/react-router-dom
 * @typescript-eslint/eslint-plugin
 * @typescript-eslint/parser
 * confusing-browser-globals
 * csstype
 * eslint
 * eslint-config-airbnb
 * eslint-config-prettier
 * eslint-plugin-babel
 * eslint-plugin-import
 * eslint-plugin-jest
 * eslint-plugin-jsdoc
 * eslint-plugin-prettier
 * eslint-plugin-react
 * eslint-plugin-react-hooks
 * eslint-plugin-tsdoc
 * husky
 * prettier

В качестве менеджера пакетов использовать только yarn. Установка пакетов делается через команду yarn add. Для установки dev-зависимости используется флаг -D

В package.json перенести в devDependencies пакеты:
 * @testing-library/jest-dom
 * @testing-library/react
 * @testing-library/user-event
 * @types/jest
 * @types/node
 * @types/react
 * @types/react-dom

**Comment by Evgenie** [comment]
Задача сделана полностью в соответствии с описанием
