### ISSUE TITLE
Для примера examples/react-uikit в директории ./src задать следующую структуру для исходников:

### ISSUE THREAD

**Issue by LordWerter** [LordWerter/fast-js#3]
Для примера examples/react-uikit в директории ./src задать следующую структуру для исходников:
- epics    // раздел для эпиков. Эпик = модуль 
      * App // компонент основного приложения
      * Welcome // компонент-страница для главной страницы приложения, которая грузится по урлу "/"
      * Contacts // компонент-страница для главной страницы приложения, которая грузится по урлу "/contacts/"
- features // раздел с фитчами. Обычно одна фитча = одна задача в WorkFlow команд разработки
      * ImageSlides // компонент слайдера с картинками
- routes // раздел для кода, относящегося к роутингу внутри приложения
- theme // раздел с темой оформления для приложения
- utils // раздел с утилитами приложения. К утилитам относят отдельные функции, которые выполняют различные второстепенные действия. Например, конвертацию данных или создание объекта с заданными свойствами и тп
- index.tsx
- react-app-env.d.ts
- reportWebVitals.ts
- setupTests.ts

каждый компонент должен содержать в себе определенную структуру обязательных файлов и папок. Например, нам надо создать компонент с названием ImageSlides. Компонент является фитчей. В директории ./src/features создаем директорию с названием компонента и в директории создаем следующие файлы:
- index.ts // этот файлик нужен нам для экспорта по умолчанию нашего компонента, а также для удобства указания урла при его импорте в дальнейшем
- ImageSlides.tsx // здесь пишем наш компонент
- ImageSlides.styles.tsx // здесь пишем структурные элементы компонента, которые будут создаваться  через фреймворк @emotion, а также стилизироваться через механизм провайдера тем
- README.md // документация по компоненту
- __tests__ // директория с тестами для компонента
        * index.test.tsx // спека на наш компонент

Для каждого файла есть минимальное наполнение.
Пример для index.ts
///
import <Название_компонента> from './<Название_файла_компонента>';
export default <Название_компонента>;
///

Пример для файла компонента, например, ImageSlides.tsx:
///
import React from 'react';
// import { useTheme } from '@emotion/react';
import { CWrap } from './ImageSlides.styles';

export interface IProps {
    sizeId?: string;
    langId?: string;
    customise?: unknown;
}

export const ImageSlides: React.FC<IProps> = (props): JSX.Element => {
    const { sizeId = 'mobile', langId = 'ru', customise = null } = props;
    console.log(sizeId, langId, customise);

    return (
        <CWrap>
            {`Hello`}
        </CWrap>
    );
};

export default ImageSlides;
///

Пример для файла со стилями, например, ImageSlides.styles.tsx:
///
import styled from '@emotion/styled';
import { getCSSObj } from '../../utils';

export const CWrap = styled.div`
    ${getCSSObj}
`;
///

**Comment by Evgenie** [comment]
Создал структуру папок и файлов в соответствии с заданием
